config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "staticpages#home"
  get  "/section",    to: 'staticpages#section'
  get  "/detail",    to: 'staticpages#detail'
  get  "/history",    to: 'staticpages#history'
  get 'profiles/show'
  get 'profiles/update'
  resources :tasks, only: %i[create index new edit update] do
    member do
      patch 'task_status', to: 'task_statuses#update'
    end
    collection do
      get :search
    end
  end
  resource :profile, only: %i[show update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block_channel.rb
class BlockChannel < ApplicationRecord
  belongs_to :user
end

app/models/block_event.rb
class BlockEvent < ApplicationRecord
  belongs_to :user
end

app/models/block_user.rb
class BlockUser < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :workspace
end

app/models/section_storage.rb
class SectionStorage < ApplicationRecord
  belongs_to :section
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_taggable
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
  acts_as_taggable_on :tags
  include AASM
  enum priority: { low: 0, medium: 1, high: 2 }
  enum status: { active: 0, completed: 1 }
  scope :by_title, ->(search) { where("title ILIKE ?", "%#{search}%") if search.present? }
  scope :by_date, ->(date) { where("DATE(time_start) = ?", date) if date.present?  }
 
  aasm column: 'status' do
    state :active, initial: true
    state :completed

    event :toggle_status do
      transitions from: :active, to: :completed
      transitions from: :completed, to: :active
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks
  has_many :workspace_members
  has_many :workspaces, through: :workspace_members
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
end

app/models/user_assign.rb
class UserAssign < ApplicationRecord
  belongs_to :task
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :workspace_members
  has_many :users, through: :workspace_members
end

app/models/workspace_member.rb
class WorkspaceMember < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_task, only: [:edit, :update]
  before_action :load_tags, only: [:new, :edit] 

  def index
    @tasks = current_user.tasks
  end

  def search
    @tasks = current_user.tasks
    if params[:search_text].present?
      @tasks = @tasks.by_title(params[:search_text])
    elsif params[:search_date].present?
      if date_search?(params[:search_date])
        @tasks = @tasks.by_date(Date.parse(params[:search_date]))
      end
    end

    render :index
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.workspace_id = 1 
    if @task.save
      redirect_to tasks_path, notice: t('tasks.create.success')
    else
      load_tags
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was successfully updated.'
    else
      load_tags 
      render :edit
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status, :time_start, :time_end, :priority, :tag_list)
  end

  def load_task
    @task = Task.find(params[:id])
  end

  def load_tags
    @tags = ActsAsTaggableOn::Tag.limit(50) 
  end

  def date_search?(search)
    Date.parse(search) rescue false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Neli todo list'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def random_color
    '#' + format('%06x', (rand * 0xffffff)).to_s
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/task_statuses_helper.rb
module TaskStatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def display_task_time(task)
    start_time = l(task.time_start, format: :long)
    end_time = l(task.time_end, format: :long)
    "#{start_time} -- #{end_time}"
  end
end

app/views/layouts/_rails_default.html.erb
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<!-- CSS Files -->
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', rel: 'stylesheet' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %> </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <%= render 'layouts/rails_default' %>
    
  </head>

  <body>
    <% unless user_signed_in? %>
      <div class="wrapper bg-white">
        <div class="content p-0 m-0">
          <% if notice %>
            <p class="notice alert-danger text-danger text-center py-2"><%= notice %></p>
          <% end %>
          <% if alert %>
          <p class="alert bg-danger text-white text-center"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    <% else %>
      <div class="wrapper">
        <%= render 'layouts/shared/side_bar' %>
        <div class="main-panel">
          <!-- Navbar -->
          <%= render 'layouts/shared/top_nav_bar' %>
          <!-- End Navbar -->
          <div class="content">
            <%= yield %>
          </div>
        </div>
      </div>
    <% end %>
    
  </body>
</html>

app/views/layouts/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('errors.template.header', count: object.errors.count, model: object.model_name.human.downcase) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_side_bar.html.erb
<div class="sidebar" data-color="purple" data-background-color="white" data-image=<%= asset_path('sidebar-1.jpg') %>>
<div class="logo">
    <a href="/" class="simple-text logo-normal">
      <img class="logo-img" src=<%= asset_path('logo.png') %> alt="Neli-logo"/>
      Neli todo list
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item active mb-4">
          <a href="#" class="nav-link">
            <i class="material-icons">add</i>
            <p>Thêm Workspace</p>
          </a>
      </li>
      <% if @workspaces.present? %>
        <% @workspaces.each do |w| %>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <div class="d-flex justify-content-between">
                <i class="material-icons">library_books</i>
                <span class="w-75"><%= w.name %></span>
                <i class="material-icons add-item">add</i>
              </div>
            </a>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/shared/_top_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="collapse navbar-collapse justify-content-start">
      <%= form_tag search_tasks_path, method: :get, remote: true, class: 'navbar-form navbar-bg-custom border rounded border-light search-form' do %>
        <div class="form-inline my-2 my-lg-0 position-relative">
          <i class="material-icons mx-2">search</i>
          <%= text_field_tag 'search_text', params[:search_text], placeholder: 'Tìm kiếm', class: 'form-control mr-sm-2 w-75 search-input search-text' %>
          <%= text_field_tag 'search_date', params[:search_date], placeholder: 'Chọn ngày', class: 'form-control mr-sm-2 w-75 search-input datetimepicker', style: 'display:none;' %>
          <i class="material-icons datetimepicker-icon">calendar_today</i>
        </div>
      <% end %>
    </div>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item dropdown show">
          <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons">notifications</i>
            <span class="notification">5</span>
            <p class="d-lg-none d-md-block">
              Some Actions
            </p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Mike John responded to your email</a>
            <a class="dropdown-item" href="#">You have 5 new tasks</a>
            <a class="dropdown-item" href="#">You're now friend with Andrew</a>
            <a class="dropdown-item" href="#">Another Notification</a>
            <a class="dropdown-item" href="#">Another One</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons">person</i>
            <p class="d-lg-none d-md-block">
              Account
            </p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
            <%= link_to 'Profile', profile_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              Log out
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>