config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "staticpages#home"
  get  "/section",    to: 'staticpages#section'
  get  "/detail",    to: 'staticpages#detail'
  get  "/history",    to: 'staticpages#history'
  get 'profiles/show'
  get 'profiles/update'
  resources :tasks, only: %i[create index new edit update] do
    member do
      patch 'task_status', to: 'task_statuses#update'
    end
    collection do
      get :search
    end
  end
  resource :profile, only: %i[show update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block_channel.rb
class BlockChannel < ApplicationRecord
  belongs_to :user
end

app/models/block_event.rb
class BlockEvent < ApplicationRecord
  belongs_to :user
end

app/models/block_user.rb
class BlockUser < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :workspace
end

app/models/section_storage.rb
class SectionStorage < ApplicationRecord
  belongs_to :section
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_taggable
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
  acts_as_taggable_on :tags
  include AASM
  enum priority: { low: 0, medium: 1, high: 2 }
  enum status: { active: 0, completed: 1 }
  scope :by_title, ->(search) { where("title ILIKE ?", "%#{search}%") if search.present? }
  scope :by_date, ->(date) { where("DATE(time_start) = ?", date) if date.present?  }
 
  aasm column: 'status' do
    state :active, initial: true
    state :completed

    event :toggle_status do
      transitions from: :active, to: :completed
      transitions from: :completed, to: :active
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks
  has_many :workspace_members
  has_many :workspaces, through: :workspace_members
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
end

app/models/user_assign.rb
class UserAssign < ApplicationRecord
  belongs_to :task
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :workspace_members
  has_many :users, through: :workspace_members
end

app/models/workspace_member.rb
class WorkspaceMember < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_workspaces
  before_action :set_locale

  private

  def set_workspaces
    @workspaces = current_user.workspaces if user_signed_in?
  end

  def set_locale
    I18n.locale = :en
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @current_user
  end

  def update
    if @current_user.update(user_params)
      flash[:notice] = t('profiles.update.success')
      redirect_to profile_path
    else
      flash[:alert] = t('profiles.update.failure')
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :number, :username) 
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home; end

  def section; end

  def detail; end

  def history; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_task, only: [:edit, :update]
  before_action :load_tags, only: [:new, :edit] 

  def index
    @tasks = current_user.tasks
  end

  def search
    @tasks = current_user.tasks
    if params[:search_text].present?
      @tasks = @tasks.by_title(params[:search_text])
    elsif params[:search_date].present?
      if date_search?(params[:search_date])
        @tasks = @tasks.by_date(Date.parse(params[:search_date]))
      end
    end

    render :index
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.workspace_id = 1 
    if @task.save
      redirect_to tasks_path, notice: t('tasks.create.success')
    else
      load_tags
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was successfully updated.'
    else
      load_tags 
      render :edit
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status, :time_start, :time_end, :priority, :tag_list)
  end

  def load_task
    @task = Task.find(params[:id])
  end

  def load_tags
    @tags = ActsAsTaggableOn::Tag.limit(50) 
  end

  def date_search?(search)
    Date.parse(search) rescue false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Neli todo list'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def random_color
    '#' + format('%06x', (rand * 0xffffff)).to_s
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/task_statuses_helper.rb
module TaskStatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def display_task_time(task)
    start_time = l(task.time_start, format: :long)
    end_time = l(task.time_end, format: :long)
    "#{start_time} -- #{end_time}"
  end
end

app/views/tasks/_form.html.erb
<%= render 'layouts/shared/error_message', object: form.object %>

<div class="form-group">
  <%= form.label :title, t('.label.title'), class: "text-dark" %>
  <%= form.text_field :title, placeholder: t('.placeholder.title'), class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :description, t('.label.description'), class: "text-dark" %>
  <%= form.text_area :description, placeholder: t('.placeholder.description'), class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :status, t('.label.status'), class: "text-dark" %>
  <%# form.text_field :status %>
  <div class="d-flex">
    <% Task.statuses.keys.each do |status| %>
      <div class="form-check mx-3">
        <%= form.radio_button :status, status, id: "status_#{status}" %>
        <%= form.label "status_#{status}", status.humanize %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6 col-sm-12">
    <%= form.label :time_start, t('.label.start'), class: "text-dark" %>
    <%= form.datetime_select :time_start, class: "form-control" %>
  </div>

  <div class="form-group col-md-6 col-sm-12">
    <%= form.label :time_end, t('.label.end'), class: "text-dark" %>
    <%= form.datetime_select :time_end, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= form.label :priority, t('.label.priority'), class: "text-dark" %>
  <div class="priority-selector">
    <% Task.priorities.keys.each do |priority| %>
      <div class="form-check">
        <%= form.radio_button :priority, priority, id: "priority_#{priority}" %>
        <%= form.label "priority_#{priority}", priority.humanize %>
      </div>
    <% end %>
  </div>
</div>

<div class="selected-tags">
  <strong>Tag:</strong>
  <div class="selected-tags-container">
    <% if @task.tag_list.present? %>
      <% @task.tag_list.each do |tag| %>
        <span class="selected-tag" data-tag="<%= tag %>">
          <%= tag %>
          <button type="button" class="remove-tag">x</button>
        </span>
      <% end %>
    <% end %>
  </div>
  <%= form.hidden_field :tag_list, class: 'tag-list-field' %>
</div>

<div class="available-tags mt-3">
  <% if @tags.present? %>
    <% @tags.each do |tag| %>
      <span class="tag" data-tag="<%= tag.name %>" style="background-color: <%= random_color %>"><%= tag.name %></span>
    <% end %>
  <% else %>
    <p>No tags available</p>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<% @tasks.each do |task| %>
  <div id="task-<%= task.id %>" class="task-item">
    <div class="row">
      <div class="col-4">
        <%= form_with url: task_status_task_path(task), method: :patch, remote: true, class: "form-group form-check toggle-task-form" do %>
          <%= check_box_tag :completed, 'true', task.completed?, class: "form-check-input toggle-task", id: "task-#{task.id}-checkbox", onchange: "this.form.submit();" %>
          <label class="form-check-label text-dark" id="task-<%= task.id %>-label" for="task-<%= task.id %>-checkbox">
            <% if task.completed? %>
              <del><%= task.title %></del>
            <% else %>
              <%= task.title %>
            <% end %>
          </label>
        <% end %>
        <p><%= task.description %></p>
      </div>
      <div class="col-5">
        <p><%= display_task_time(task) %></p>
      </div>
      <div class="col-1">
        <%= link_to edit_task_path(task), class: "btn btn-secondary btn-edit py-2 px-3" do %>
          <i class="material-icons">edit_note</i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container bg-white rounded p-4">
  <h3><%= t('.title') %></h3>

  <%= form_with(model: @task, url: task_path(@task), local: true) do |form| %>
    <%= render 'tasks/form', form: form %>
    <%= form.submit t('.submit'), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container bg-white rounded">
  <aside>
    <section class="task">
      <div class="task-header d-flex justify-content-between">
        <h3> <%= t('.title') %> </h3>
        <%= link_to new_task_path, class: 'btn btn-primary' do %>
          <%= t('.button.add') %>
        <% end %>
      </div>
      
      <% if params[:search_text].present? || params[:search_date].present? %>
        <% if @tasks.any? %>
          <ul>
            <%= render 'tasks/task' %>
          </ul>
        <% else %>
          <div class="d-flex justify-content-center">
            <p><%= t('.noData') %></p>
          </div>
        <% end %>
      <% else %>
        <ul>
          <%= render 'tasks/task' %>
        </ul>
      <% end %>
    </section>
  </aside>
</div>

app/views/tasks/new.html.erb
<div class="container bg-white rounded p-4">
  <h3><%= t('.title') %></h3>

  <%= form_with(model: @task, url: tasks_path, local: true) do |form| %>
    <%= render 'layouts/shared/error_message', object: form.object %>

    <div class="form-group">
      <%= form.label :title, t('.label.title'), class: "text-dark" %>
      <%= form.text_field :title, placeholder: t('.placeholder.title'), class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description, t('.label.description'), class: "text-dark" %>
      <%= form.text_area :description, placeholder: t('.placeholder.description'), class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :status, t('.label.status'), class: "text-dark" %>
      <%= form.number_field :status %>
    </div>

    <div class="row">
      <div class="form-group col-md-6 col-sm-12">
        <%= form.label :time_start, t('.label.start'), class: "text-dark" %>
        <%= form.datetime_select :time_start, class: "form-control" %>
      </div>

      <div class="form-group col-md-6 col-sm-12">
        <%= form.label :time_end, t('.label.end'), class: "text-dark" %>
        <%= form.datetime_select :time_end, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :priority, t('.label.priority'), class: "text-dark" %>
      <div class="priority-selector">
        <% Task.priorities.keys.each do |priority| %>
          <div class="form-check">
            <%= form.radio_button :priority, priority, id: "priority_#{priority}" %>
            <%= form.label "priority_#{priority}", priority.humanize %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="selected-tags">
      <strong>Tag:</strong>
      <div class="selected-tags-container">
        <% if @task.tag_list.present? %>
          <% @task.tag_list.each do |tag| %>
            <span class="selected-tag" data-tag="<%= tag %>">
              <%= tag %>
              <button type="button" class="remove-tag">x</button>
            </span>
          <% end %>
        <% end %>
      </div>
      <%= form.hidden_field :tag_list, class: 'tag-list-field' %>
    </div>

    <div class="available-tags mt-3">
      <% @tags.each do |tag| %>
        <span class="tag" data-tag="<%= tag.name %>" style="background-color: <%= random_color %>"><%= tag.name %></span>
      <% end %>
    </div>

    <%= form.submit t('.submit'), class: "btn btn-primary" %>
  <% end %>
</div>