config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "staticpages#home"
  get  "/section",    to: 'staticpages#section'
  get  "/detail",    to: 'staticpages#detail'
  get  "/history",    to: 'staticpages#history'
  get 'profiles/show'
  get 'profiles/update'
  resources :tasks, only: %i[create index new edit update] do
    member do
      patch 'task_status', to: 'task_statuses#update'
    end
    collection do
      get :search
    end
  end
  resource :profile, only: %i[show update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block_channel.rb
class BlockChannel < ApplicationRecord
  belongs_to :user
end

app/models/block_event.rb
class BlockEvent < ApplicationRecord
  belongs_to :user
end

app/models/block_user.rb
class BlockUser < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :workspace
end

app/models/section_storage.rb
class SectionStorage < ApplicationRecord
  belongs_to :section
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_taggable
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
  acts_as_taggable_on :tags
  include AASM
  enum priority: { low: 0, medium: 1, high: 2 }
  enum status: { active: 0, completed: 1 }
  scope :by_title, ->(search) { where("title ILIKE ?", "%#{search}%") if search.present? }
  scope :by_date, ->(date) { where("DATE(time_start) = ?", date) if date.present?  }
 
  aasm column: 'status' do
    state :active, initial: true
    state :completed

    event :toggle_status do
      transitions from: :active, to: :completed
      transitions from: :completed, to: :active
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks
  has_many :workspace_members
  has_many :workspaces, through: :workspace_members
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
end

app/models/user_assign.rb
class UserAssign < ApplicationRecord
  belongs_to :task
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :workspace_members
  has_many :users, through: :workspace_members
end

app/models/workspace_member.rb
class WorkspaceMember < ApplicationRecord
  belongs_to :workspace
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @current_user
  end

  def update
    if @current_user.update(user_params)
      flash[:notice] = t('profiles.update.success')
      redirect_to profile_path
    else
      flash[:alert] = t('profiles.update.failure')
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :number, :username) 
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_task, only: [:edit, :update]
  before_action :load_tags, only: [:new, :edit] 

  def index
    @tasks = current_user.tasks
  end

  def search
    @tasks = current_user.tasks
    if params[:search_text].present?
      @tasks = @tasks.by_title(params[:search_text])
    elsif params[:search_date].present?
      if date_search?(params[:search_date])
        @tasks = @tasks.by_date(Date.parse(params[:search_date]))
      end
    end

    render :index
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.workspace_id = 1 
    if @task.save
      redirect_to tasks_path, notice: t('tasks.create.success')
    else
      load_tags
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was successfully updated.'
    else
      load_tags 
      render :edit
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status, :time_start, :time_end, :priority, :tag_list)
  end

  def load_task
    @task = Task.find(params[:id])
  end

  def load_tags
    @tags = ActsAsTaggableOn::Tag.limit(50) 
  end

  def date_search?(search)
    Date.parse(search) rescue false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Neli todo list'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def random_color
    '#' + format('%06x', (rand * 0xffffff)).to_s
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/task_statuses_helper.rb
module TaskStatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def display_task_time(task)
    start_time = l(task.time_start, format: :long)
    end_time = l(task.time_end, format: :long)
    "#{start_time} -- #{end_time}"
  end
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <div class="alert-danger rounded p-2"> 
      <span class="text-danger">
        <%= I18n.t("errors.messages.not_saved",
                  count: resource.errors.count,
                  resource: resource.class.model_name.human.downcase)
        %>
      </span>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class="d-flex g-2">
    <span class="pr-2 font-weight-normal">Already have account?</span>
    <%= link_to "Log in", new_session_path(resource_name) %>
  </div>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class="d-flex">
    <span class="pr-2 font-weight-normal">Don't have account?</span>
    <%= link_to "Sign up", new_registration_path(resource_name) %>
  </div>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/shared/_logo_branch.html.erb
<div class="logo mb-4">
  <a href="/" class="simple-text d-flex flex-column align-items-center">
    <img class="logo-img w-25 m-0" src=<%= asset_path('logo.png') %> alt="Neli-logo"/>
    <h3 class="text-dark font-weight-bold mt-2">Neli todo list</h3>
  </a>
</div>